"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// infra/lambdas/afu9_patch_generator.ts
var afu9_patch_generator_exports = {};
__export(afu9_patch_generator_exports, {
  handler: () => handler
});
module.exports = __toCommonJS(afu9_patch_generator_exports);
var handler = async (event) => {
  console.log("AFU-9 PatchGenerator v0.1", { event });
  const branchBase = event.issue?.number ? `afu9/issue-${event.issue.number}` : `afu9/manual-${Date.now()}`;
  const patch = {
    description: "AFU-9 v0.1 stub patch",
    branchName: branchBase,
    files: [
      {
        path: "AFU9_AUTOGENERATED_NOTE.md",
        content: `# AFU-9 Autogenerated Note

Dies ist ein automatisch erstellter Commit von AFU-9 v0.1.

Repo: ${event.repo}
` + (event.issue ? `Issue: #${event.issue.number} - ${event.issue.title}
` : `Issue: n/a (manueller Trigger)
`)
      }
    ]
  };
  return {
    ...event,
    patch
  };
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  handler
});
