interface IssueContextState {
  repo: string;
  targetBranch: string;
  issue?: {
    number: number;
    title: string;
    body: string;
  } | null;
}

interface Patch {
  description: string;
  branchName: string;
  files: Array<{
    path: string;
    content: string;
  }>;
}

export const handler = async (event: IssueContextState): Promise<any> => {
  console.log("AFU-9 PatchGenerator v0.1", { event });

  const branchBase = event.issue?.number
    ? `afu9/issue-${event.issue.number}`
    : `afu9/manual-${Date.now()}`;

  const patch: Patch = {
    description: "AFU-9 v0.1 stub patch",
    branchName: branchBase,
    files: [
      {
        path: "AFU9_AUTOGENERATED_NOTE.md",
        content:
          `# AFU-9 Autogenerated Note\n\n` +
          `Dies ist ein automatisch erstellter Commit von AFU-9 v0.1.\n\n` +
          `Repo: ${event.repo}\n` +
          (event.issue
            ? `Issue: #${event.issue.number} - ${event.issue.title}\n`
            : `Issue: n/a (manueller Trigger)\n`)
      }
    ]
  };

  return {
    ...event,
    patch
  };
};
