import { Octokit } from "octokit";
import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

const GITHUB_TOKEN = process.env.AFU9_GITHUB_TOKEN!;

interface PatchState {
  repo: string;
  targetBranch: string;
  patch: {
    description: string;
    branchName: string;
    files: Array<{
      path: string;
      content: string;
    }>;
  };
  issue?: {
    number: number;
    title: string;
    body: string;
  } | null;
}

export const handler = async (event: PatchState) => {
  console.log("AFU-9 PRCreator v0.1", { event });

  const [owner, repo] = event.repo.split("/");
  const octokit = new Octokit({ auth: GITHUB_TOKEN });

  const workdir = fs.mkdtempSync(path.join(os.tmpdir(), "afu9-"));
  console.log("Working directory:", workdir);

  execSync(`git clone https://github.com/${owner}/${repo}.git .`, {
    cwd: workdir,
    stdio: "inherit"
  });
  execSync(`git checkout ${event.targetBranch}`, {
    cwd: workdir,
    stdio: "inherit"
  });

  const branchName = event.patch.branchName;
  execSync(`git checkout -b ${branchName}`, {
    cwd: workdir,
    stdio: "inherit"
  });

  for (const file of event.patch.files) {
    const filePath = path.join(workdir, file.path);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, file.content, "utf8");
  }

  execSync(`git add .`, { cwd: workdir, stdio: "inherit" });
  execSync(`git commit -m "AFU-9 v0.1: autogenerated patch"`, {
    cwd: workdir,
    stdio: "inherit"
  });
  execSync(`git push origin ${branchName}`, {
    cwd: workdir,
    stdio: "inherit"
  });

  const prTitle = event.issue
    ? `AFU-9: Fix for Issue #${event.issue.number} (v0.1 stub)`
    : `AFU-9: Autogenerated Patch (v0.1 stub)`;

  const prBody =
    (event.issue
      ? `Bezug auf Issue #${event.issue.number}: ${event.issue.title}\n\n`
      : `Manuell ausgelöster AFU-9 v0.1 Job.\n\n`) +
    `Beschreibung:\n${event.patch.description}\n\n` +
    `Hinweis: v0.1 ist ein Walking Skeleton und generiert nur einfache Änderungen.`;

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: prTitle,
    head: branchName,
    base: event.targetBranch,
    body: prBody
  });

  console.log("Created PR:", pr.html_url);

  return {
    ...event,
    prUrl: pr.html_url,
    prNumber: pr.number
  };
};
