#!/bin/bash
# Manual Verification Script for E89.7: Publish Audit Trail
# 
# This script provides commands to verify the implementation

echo "=== E89.7 Publish Audit Trail Verification ==="
echo ""
echo "1. Database Migration"
echo "   Run: npm run db:migrate"
echo "   Verify: Check that migration 071 has been applied"
echo ""
echo "2. Verify database schema (requires running database)"
echo "   psql \$DATABASE_URL -c \"\\d intent_issue_set_publish_batch_events\""
echo "   Should show result_json and result_truncated columns"
echo ""
echo "3. Verify API endpoint (requires running server)"
echo "   curl -H 'x-afu9-sub: test-user' \\"
echo "        http://localhost:3000/api/intent/sessions/SESSION_ID/publish-batches"
echo ""
echo "4. Verify UI"
echo "   - Navigate to /intent in the UI"
echo "   - Click 'Publish History' button"
echo "   - Verify that the panel opens and shows batches (if any exist)"
echo ""
echo "5. Test result_json truncation"
echo "   - Create a publish batch with large result_json"
echo "   - Verify that result_truncated is set to true"
echo ""
echo "6. Test deterministic ordering"
echo "   - Create multiple batches for a session"
echo "   - Query the API endpoint"
echo "   - Verify batches are ordered by created_at DESC, batch_id ASC"
echo ""
echo "=== PowerShell Commands for Repository Verification ==="
echo ""
echo "# Build verification"
echo "npm --prefix control-center run build"
echo ""
echo "# Test verification"  
echo "npm --prefix control-center test"
echo ""
echo "# Repository verification"
echo "npm run repo:verify"
echo ""
